# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "hbase-phoenix"

  config.vm.box_check_update = false
  config.vbguest.auto_update = false

  config.vm.define "hbase_pnx" do |hbase_pnx|

    hbase_pnx.vm.hostname = "hbasepnx"
    hbase_pnx.vm.network "private_network", ip: "192.168.99.101"
    hbase_pnx.vm.network "forwarded_port", guest: 2181, host: 2181
    hbase_pnx.vm.network "forwarded_port", guest: 16010, host: 16010

  end

end
